package com.openclassrooms.paymybuddy.model;

import javax.persistence.*;

@Entity
@Table(name = "role_profile")
public class RoleProfile {
    /**
     * ID, generated by DataBase.
     * Use as primary key in DataBase.
     */
    @Id
    @Column(name = "role_id")
    private int id;

    /**
     * Role name defined.
     */
    @Column(name = "role_name")
    private String name;

    /**
     * Public constructor.
     * @param name .
     */
    public RoleProfile(int id, String name) {
        this.id = id;
        this.name = name;
    }

    private RoleProfile() { }

    /**
     * Getter ID.
     * @return ID
     */
    public int getId() {
        return id;
    }

    /**
     * Setter ID.
     * ID is auto-generated, should not be accessible.
     * @param pId to set
     */
    private void setId(final int pId) {
        id = pId;
    }

    public String getName() {
        return name;
    }

    public void setName(String pName) {
        name = pName;
    }
}
