package com.openclassrooms.paymybuddy.model;

import javax.persistence.*;
import java.util.List;

@Entity
@Table(name = "role_profile")
public class RoleProfile {
    /**
     * ID, generated by DataBase.
     * Use as primary key in DataBase.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "role_id")
    private int id;

    /**
     * Role name defined by RoleType enum.
     * @see RoleType
     */
    @Column(name = "role_name")
    private RoleType name;

    /**
     * List of all user account which benefits of this role.
     * @see UserAccount
     */
    @ManyToMany(mappedBy = "roles")
    private List<UserAccount> users;
}
